from twitter_auth import CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET
import pickle
import tweepy
import os.path
import time

# File containing a list of tweets generated by gen_trump_tweets.py
TWEET_FILE = "generated_trump_tweets.pickle"
# File in which the status of the bot (which tweets it already tweeted) is saved
STATUS_FILE = "botstatus.pickle"

# Tweet every 20 minutes
TWEET_INTERVAL = 20 * 60  

# Log into twitter
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

# Load status
cur_index = 0
if os.path.isfile(STATUS_FILE):
    cur_index = pickle.load(open(STATUS_FILE, "rb"))

# Load pre-generated tweets
tweets = []
with open(TWEET_FILE, "rb") as tweet_file:
    tweets = pickle.load(tweet_file)

# Tweet next tweet every TWEET_INTERVAL
while True:
    tweet = tweets[cur_index]
    api.update_status(tweet[:140])
    cur_index += 1
    pickle.dump(cur_index, open(STATUS_FILE, "wb"))
    time.sleep(TWEET_INTERVAL)
